//
//  UsersWorker.swift
//  Kaidee Assignment
//
//  Created by Peerapat Prommaha on 18/3/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Moya

class UsersWorker {
    
    func getUsers(completion: @escaping (Result<[UserModel]?, CommonError>) -> Void) {
        let provider = MoyaProvider<UserServices>()
        provider.request(UserServices.getUsers) { result in
            switch result {
            case let .success(response):
                let jsonData = response.data
                let result = try? JSONDecoder().decode([UserModel].self, from: jsonData)
                completion(.success(result))
            case let .failure(error):
                let commonError = CommonError(status: error.errorCode, error: error.localizedDescription)
                completion(.failure(commonError))
            }
        }
    }
    
    func searchUsers(request: Users.SearchUsers.Request, completion: @escaping (Result<SearchUserModel?, CommonError>) -> Void) {
        let provider = MoyaProvider<UserServices>()
        provider.request(UserServices.searchUsers(userName: request.userName)) { result in
            switch result {
            case let .success(response):
                let jsonData = response.data
                let result = try? JSONDecoder().decode(SearchUserModel.self, from: jsonData)
                completion(.success(result))
            case let .failure(error):
                let commonError = CommonError(status: error.errorCode, error: error.localizedDescription)
                completion(.failure(commonError))
            }
        }
    }
}
